name: CommandFramework
version: '1.0-SNAPSHOT'
main: fr.zeyx.commandframework.CommandFramework
api-version: '1.21'
authors: [ ZeyX_ ]
description: Library using annotations to easily create Minecraft commands for plugins.
commands:
  heal:
    description: "Heal un joueur"
  murder_mystery:
    description: "balablalabl"
